version: '3.8'
services:
  server:
    build: ./server
    env_file: ./server/.env
    ports:
      - "3000:3000"
  client:
    build: ./client
    env_file: ./client/.env
    ports:
      - "5173:5173"
